### ISSUE TITLE
Error parsing HTTP request

### ISSUE THREAD

**Issue by renatofritola** [Alfresco/alfresco-transform-core#417]
Hi,
I'm getting the error below when starting Transform Core 2.4 for alfresco community version 7.0.0.

`
2021-06-02 14:52:30.101  INFO 1 --- [nio-8090-exec-1] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x030x010xaa0x010x000x010xa60x030x030x990x8a0xbeVk0xff0x0d-0xf90xb9;0x880xc030x8bja0xb40xdf0xa40xcf0x9e0xd5!u:50xbd0x0fN0xddm]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:418) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2021-06-02 14:52:30.103  INFO 1 --- [nio-8090-exec-2] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x030x010xaa0x010x000x010xa60x030x030xa8.0xa10xc60x870xb20x19<y&0xe90xa60x030x18^0xc3>0x01u0x0eb&0xcf1$\0xc40x9f0xc6l0xfau]. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:418) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:260) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.36.jar!/:9.0.36]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
`

**Comment by montgolfiere** [comment]
Hi @renatofritola Can you confirm details of your dev/test environment and steps you used to build and run ?

Are you compiling & running with JDK 11 (eg. Open JDK 11.0.10) ?

**Comment by renatofritola** [comment]
Hi @montgolfiere.
I'm using docker environment based on docker-compose provided by acs-deployment project.
The docker-compose is available at: https://github.com/Alfresco/acs-deployment/blob/master/docker-compose/community-docker-compose.yml

In this compose the transform-core-aio 2.4 image is used and it uses open-jdk 11 as below:

> openjdk version "11.0.11" 2021-04-20 LTS
> OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
> OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)

**Comment by montgolfiere** [comment]
@renatofritola That's odd. Please ensure you have allocated at least 16 Gb to the Docker Engine. 

I'm just trying it as well. I'm using most recent release tag (eg. v5.1.0-M1) rather than master. However, both currently reference transform-core-aio:2.4.0.

https://github.com/Alfresco/acs-deployment/blob/v5.1.0-M1/docker-compose/community-docker-compose.yml

Here are my current versions (running on Docker on macOS):

```
% docker -v
Docker version 20.10.6, build 370c289
% docker-compose -v
docker-compose version 1.29.1, build c34c88b2
```
It starts ok for me using "docker-compose -f community-docker-compose.yml up". For example:

```
% docker-compose logs transform-core-aio
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.4.5)

2021-06-04 16:23:41.591  INFO 1 --- [           main] org.alfresco.transformer.Application     : Starting Application v2.4.0 using Java 11.0.11 on a14c7925ff5a with PID 1 (/usr/bin/alfresco-transform-core-aio-boot.jar started by transform-all-in-one in /)
2021-06-04 16:23:41.600  INFO 1 --- [           main] org.alfresco.transformer.Application     : No active profile set, falling back to default profiles: default
2021-06-04 16:23:43.924  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8090 (http)
2021-06-04 16:23:43.940  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-06-04 16:23:43.941  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.45]
2021-06-04 16:23:44.012  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-06-04 16:23:44.012  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 2219 ms
2021-06-04 16:23:44.803  WARN 1 --- [           main] o.a.p.p.font.FileSystemFontProvider      : New fonts found, font cache will be re-built
2021-06-04 16:23:44.803  WARN 1 --- [           main] o.a.p.p.font.FileSystemFontProvider      : Building on-disk font cache, this may take a while
2021-06-04 16:23:45.088  WARN 1 --- [           main] o.a.p.p.font.FileSystemFontProvider      : Finished building on-disk font cache, found 57 fonts
2021-06-04 16:23:45.089  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Times-Roman
2021-06-04 16:23:45.104  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Times-Bold
2021-06-04 16:23:45.113  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Times-Italic
2021-06-04 16:23:45.116  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Times-BoldItalic
2021-06-04 16:23:45.130  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Helvetica
2021-06-04 16:23:45.136  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Helvetica-Bold
2021-06-04 16:23:45.138  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Helvetica-Oblique
2021-06-04 16:23:45.140  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Helvetica-BoldOblique
2021-06-04 16:23:45.148  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Courier
2021-06-04 16:23:45.152  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Courier-Bold
2021-06-04 16:23:45.159  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Courier-Oblique
2021-06-04 16:23:45.161  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Courier-BoldOblique
2021-06-04 16:23:45.162  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font Symbol
2021-06-04 16:23:45.163  WARN 1 --- [           main] o.a.pdfbox.pdmodel.font.PDType1Font      : Using fallback font LiberationSans for base font ZapfDingbats
2021-06-04 16:23:47.139  INFO 1 --- [           main] o.a.j.office.ProcessPoolOfficeManager    : ProcessManager implementation is LinuxProcessManager
2021-06-04 16:23:47.198  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : Using original OpenOffice command: [/opt/libreoffice6.3/program/soffice.bin, -accept=socket,host=127.0.0.1,port=8100;urp;, -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100, -headless, -nocrashreport, -nodefault, -nofirststartwizard, -nolockcheck, -nologo, -norestore]
2021-06-04 16:23:47.199  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100'
2021-06-04 16:23:47.203  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : started process; pid = 54
2021-06-04 16:23:48.871  WARN 1 --- [ProcessThread-0] o.a.j.office.ManagedOfficeProcess        : office process died with exit code 81; restarting it
2021-06-04 16:23:48.874  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : Using original OpenOffice command: [/opt/libreoffice6.3/program/soffice.bin, -accept=socket,host=127.0.0.1,port=8100;urp;, -env:UserInstallation=file:///tmp/.jodconverter_socket_host-127.0.0.1_port-8100, -headless, -nocrashreport, -nodefault, -nofirststartwizard, -nolockcheck, -nologo, -norestore]
2021-06-04 16:23:48.875  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : starting process with acceptString 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1' and profileDir '/tmp/.jodconverter_socket_host-127.0.0.1_port-8100'
2021-06-04 16:23:48.881  INFO 1 --- [ProcessThread-0] o.a.jodconverter.office.OfficeProcess    : started process; pid = 63
2021-06-04 16:23:49.553  INFO 1 --- [ProcessThread-0] o.a.j.office.OfficeConnection            : connected: 'socket,host=127.0.0.1,port=8100,tcpNoDelay=1'
2021-06-04 16:23:49.761  INFO 1 --- [           main] o.m.pooled.jms.JmsPoolConnectionFactory  : Provided ConnectionFactory implementation is JMS 2.0+ capable.
2021-06-04 16:23:49.848  INFO 1 --- [           main] o.a.transformer.messaging.MessagingInfo  : JMS client is DISABLED - ACTIVEMQ_URL is not set
2021-06-04 16:23:50.299  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-06-04 16:23:51.409  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 3 endpoint(s) beneath base path '/actuator'
2021-06-04 16:23:51.582  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8090 (http) with context path ''
2021-06-04 16:23:51.622  INFO 1 --- [           main] org.alfresco.transformer.Application     : Started Application in 11.557 seconds (JVM running for 13.055)
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : --------------------------------------------------------------------------------------------------------------------------------------------------------------
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : If the Alfresco software was purchased under a paid Alfresco license, the terms of the paid license agreement 
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : will prevail. Otherwise, the software is provided under terms of the GNU LGPL v3 license. 
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : See the license at http://www.gnu.org/licenses/lgpl-3.0.txt. or in /LICENSE.txt 
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses ImageMagick from ImageMagick Studio LLC. See the license at http://www.imagemagick.org/script/license.php or in /ImageMagick-license.txt
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses LibreOffice from The Document Foundation. See the license at https://www.libreoffice.org/download/license/ or in /libreoffice.txt
2021-06-04 16:23:51.676  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses Tika from Apache. See the license at http://www.apache.org/licenses/LICENSE-2.0. or in /Apache\ 2.0.txt
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses ExifTool by Phil Harvey. See license at https://exiftool.org/#license. or in /Perl-Artistic-License.txt
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses alfresco-pdf-renderer which uses the PDFium library from Google Inc. See the license at https://pdfium.googlesource.com/pdfium/+/master/LICENSE or in /pdfium.txt
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : This transformer uses libraries from Apache. See the license at http://www.apache.org/licenses/LICENSE-2.0. or in /Apache\\ 2.0.txt\nAdditional libraries used:
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : * htmlparser http://htmlparser.sourceforge.net/license.html
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : --------------------------------------------------------------------------------------------------------------------------------------------------------------
2021-06-04 16:23:51.677  INFO 1 --- [           main] org.alfresco.transformer.Application     : Starting application components... Done
2021-06-04 16:24:00.588  INFO 1 --- [nio-8090-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-06-04 16:24:00.588  INFO 1 --- [nio-8090-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-06-04 16:24:00.590  INFO 1 --- [nio-8090-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2021-06-04 16:24:00.639  INFO 1 --- [nio-8090-exec-1] org.alfresco.transformer.AIOController   : GET Transform Config.
2021-06-04 16:24:00.639  INFO 1 --- [nio-8090-exec-2] org.alfresco.transformer.AIOController   : GET Transform Config.

```

**Comment by montgolfiere** [comment]
@renatofritola After successfully starting my system, I confirmed I can also reach the Transform Core test page from a browser, eg.

http://localhost:8090/

This works fine.

However, I noticed, if you incorrectly try to access via SSL, eg.

https://localhost:8090/

then you will see an error in the container log, such as:

```
transform-core-aio_1  | 2021-06-04 16:36:33.948  INFO 1 --- [nio-8090-exec-3] o.apache.coyote.http11.Http11Processor   : Error parsing HTTP request header
transform-core-aio_1  |  Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
transform-core-aio_1  | 
transform-core-aio_1  | java.lang.IllegalArgumentException: Invalid character found in method name [0x160x030x010x020x000x010x000x010xfc0x030x03h0xf70x9cG0xecW0x1c0x9fB0x170x810xe3?KR0xde!^r0x1e0x19$9*0xf00xf6H0xbb0xefUm0x04]. HTTP method names must be tokens
transform-core-aio_1  | 	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:417) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
transform-core-aio_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
transform-core-aio_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.45.jar!/:na]
transform-core-aio_1  | 	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
```

I hope this resolves your issue.
